### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by tmpringle** [MathyWizard/beneath-the-mask#1]
- [ ] Have audio dynamically transition during weather or day/night changes (probably will need to use audio files rather than YouTube videos)
- [ ] Migrate codebase to TypeScript
- [ ] Add background images or gifs, perhaps certain ones depending on weather and time (I could probably find some decent images from a longplay on YouTube)
- [ ] Refactor the `isReady` logic with the weather to instead use events
- [ ] Redo coloring on midground calendar sprites
- [ ] Clean up code where necessary (I may want to cut down on the comments and rearrange where functions are)
- [x]  **[OBSOLETE]** Add transparency toggle that allows user to hide the video player
- [x] Add weather icons
- [x] Check for weather and day/night changes once video finishes
- [x] Make a "production" version that doesn't ask for location unless requested by the user
- [x] Add calendar in top-right corner, just as it shows up in _Persona 5_
- [x] Publish the website using Github Pages and include the API key as a secret
- [x] Call the Tomorrow.io API using a backend proxy rather than calling it directly
